spring:
  datasource:
    url: jdbc:h2:mem:mydb;
    username: fiap
    password: fiap
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console:
      path: /h2-console

server:
  error:
      include-message: always