spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Livraria?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    basic:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE:register}?createDatabaseIfNotExist=true
    user: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWD:}
    schemas:
      - ${DATABASE:register}

server:
  error:
      include-message: always

jwt:
  secret: f1aPs3cr37
  expire: 5

